displacement = input("Enter your displacement")
mass = input("Enter your mass")
time = input("Enter your time")
length = input("Enter your length")
distance = length
electric_current = input("What is the value of current? ")
temperature = input("What is the value of temperature? ") 
velocity = displacement/time
voltage = input("Enter your velocity")
specific_heat_capacity = 2
ke = (int((mass*(velocity[0]**2))/2), 'J')
acceleration = (int(velocity[0]/time), 'm/s²')
force = (int(mass * acceleration[0]), 'N')
momentum = mass * velocity
breadth = int(input("Enter The Breadth"))
no_of_oscillations = int(input("Enter The no_of_oscillations"))
area = length**2
volume = length**3
pressure = force/area
work_done = force * distance
power = work_done/time
density = mass/volume
period = time/no_of_oscillations
frequency = 1/period
charge = electric_current*time
resistance = voltage/electric_current
capacitance = charge/voltage
heat_energy = mass * specific_heat_capacity * temperature